### ISSUE TITLE
[Board 49-26] cannot add Board Part xilinx.com:au280:part0:1.1

### ISSUE THREAD

**Issue by Hecmay** [Xilinx/XilinxBoardStore#358]
Hi,

I was trying to add the au280 board part (in branch 2018.3) to Vivado 2018.3. However, it seems that the board files cannot be recognized and I got this warning in the log. 
```shell
WARNING: [Board 49-26] cannot add Board Part xilinx.com:au280:part0:1.0 available at /work/shared/common/xilinx/Vivado/XilinxBoardStore/boards/Xilinx/au280/1.0/board.xml as part xcu280-fsvh2892-2l-e-es1 specified in board_part file
 is either invalid or not available
WARNING: [Board 49-26] cannot add Board Part xilinx.com:au280:part0:1.1 available at /work/shared/common/xilinx/Vivado/XilinxBoardStore/boards/Xilinx/au280/1.1/board.xml as part xcu280-fsvh2892-2l-e-es1 specified in board_part file
 is either invalid or not available
```

I also tried to open XIC and import the board files according to this post: https://forums.xilinx.com/t5/Design-Entry/WARNING-Board-49-26-cannot-add-Board-Part-xilinx-com-au200-part0/td-p/1069210

But unfortunately, XIC cannot be opened and it returned the following errors:
```shell
(test) [user@server xic]$ ./xic
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.xilinx.xic.z.a(Unknown Source)
	at com.xilinx.xic.P.b(Unknown Source)
	at com.xilinx.xic.P.<init>(Unknown Source)
	at com.xilinx.xic.z.<init>(Unknown Source)
	at com.xilinx.xic.XIC.<init>(Unknown Source)
	at com.xilinx.xic.XIC.l(Unknown Source)
	at com.xilinx.xic.XIC.main(Unknown Source)
Caused by: java.lang.IllegalArgumentException: /home/user/.Xilinx/registry/notifications.xml (No such file or directory)
	at java.xml.bind@9.0.4/javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(Unknown Source)
	at p.a.e(Unknown Source)
	at p.a.<init>(Unknown Source)
	at p.a.<clinit>(Unknown Source)
	... 7 more
```

**Comment by Premduth** [comment]
Hi, 

Please open a case with the Xilinx Tech Support on this issue. It seems something is causing XIC to crash on your machine and they can help debug the issue. The issue you are seeing seems like it is related to the device not being installed as shown in the forum post
